# to be used on ssh servers
set  -g default-terminal "screen-256color"
set  -g base-index      0
setw -g pane-base-index 0
new-session
set -g status-keys emacs
set -g mode-keys   emacs
set  -g mouse             off
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       500
set  -g history-limit     2000

# etc
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# bindings
set -g prefix M-w
bind M-w send-prefix

# unbinds
unbind C-b
unbind [          # default copy mode
unbind c          # default new window
unbind %          # default split vertical
unbind '"'        # default split horizontal
unbind x          # default kill pane
unbind &          # default kill window

# copy mode
set-window-option -g mode-keys vi
bind v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi / command-prompt -p "(search down)" "send -X search-forward \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -p "(search up)" "send -X search-backward \"%%%\""
bind-key -T copy-mode-vi n send-keys -X search-again
bind-key -T copy-mode-vi N send-keys -X search-reverse
bind-key -T copy-mode-vi Escape send-keys -X cancel

# tabs
bind Tab switch-client -T tab-prefix
bind -T tab-prefix Tab new-window -c "#{pane_current_path}"
bind -T tab-prefix d kill-window
bind -n M-h previous-window
bind -n M-l next-window

# panes
bind w switch-client -T w-prefix
bind '-' split-window -v -c "#{pane_current_path}"
bind '|' split-window -h -c "#{pane_current_path}"
bind -T w-prefix w split-window -h -c "#{pane_current_path}"
bind -T w-prefix d kill-pane
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R
