# colors
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#cdd6f4"
set -ogq @thm_mauve "#cba6f7"
set -ogq @thm_red "#f38ba8"
set -ogq @thm_yellow "#f9e2af"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_mantle "#181825"

# styling
set -g pane-border-indicators off
set -g status-position top
set -g window-status-separator ""
set -g status-left-length 0

set -g status-style "bg=#{@thm_mantle}"
set -g window-status-format "#[bg=#{@thm_overlay_2},fg=#{@thm_mantle}]#[bg=#{@thm_overlay_2},fg=#{@thm_mantle},bold] #W#{?window_zoomed_flag, ,} #[bg=#{@thm_mantle},fg=#{@thm_overlay_2}]"
set -g window-status-current-format "#[bg=#{@thm_mauve},fg=#{@thm_mantle}]#[bg=#{@thm_mauve},fg=#{@thm_mantle},bold] #W#{?window_zoomed_flag, ,} #[bg=#{@thm_mantle},fg=#{@thm_mauve}]"
set -g window-status-separator ""
set -g status-left "#[fg=#{@thm_fg} bold]#h (#S) #{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_mauve} bold]NORMAL }}"
set -g status-right ""
set -g pane-border-style "fg=#45475A"
set -g pane-active-border-style "fg=#45475A"
