bind . run-shell "sesh connect #{pane_current_path}"
bind-key s run-shell '
selected="$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi \
    --header "  ^a all ^t tmux ^x zoxide ^d kill" \
    --bind "tab:down,btab:up" \
    --bind 'ctrl-a:reload(sesh list --icons)' \
    --bind "ctrl-t:change-prompt(  )+reload(sesh list -t --icons)" \
    --bind "ctrl-x:change-prompt(󰈞  )+reload(sesh list -z --icons)" \
    --bind "ctrl-d:execute(
      name={2..};
      if sesh list -T | grep -qxF \"\$name\"; then
        tmuxinator stop \"\$name\";
      else
        tmux kill-session -t \"\$name\";
      fi
    )+reload(sesh list --icons)" \
    --preview-window "right:55%" \
    --preview "sesh preview {}" \
    -- --ansi
)"

[ -n "$selected" ] && sesh connect "$selected"
'

