# exec-once = wl-paste --type text --watch cliphist store
# exec-once = wl-paste --type image --watch cliphist store
# exec-once = systemctl --user restart xdg-desktop-portal.service
# exec-once = hyprpaper
# exec-once = hypridle
# exec-once = hyprpanel
# exec-once = keyctl link @u @s
