monitor = ,preferred,auto,1

input {
  kb_options = caps:swapescape
  kb_rules =
  follow_mouse = 0
  accel_profile = flat
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification. 
  kb_layout = us
  numlock_by_default = true
  repeat_delay = 250
  repeat_rate = 35

  touchpad {
    drag_lock = true
    natural_scroll = yes
    disable_while_typing = true
    clickfinger_behavior = true
    scroll_factor = 0.5
  }
  special_fallthrough = true
}

debug {
  disable_logs = false
  enable_stdout_logs=true
}

binds {
  # focus_window_on_workspace_c# For Auto-run stuff see execs.confhange = true
  scroll_event_delay = 0
}

gestures {
  # workspace_swipe = true
  workspace_swipe_distance = 700
  # workspace_swipe_fingers = 3
  workspace_swipe_cancel_ratio = 0.2
  workspace_swipe_min_speed_to_force = 5
  workspace_swipe_direction_lock = true
  workspace_swipe_direction_lock_threshold = 10
  workspace_swipe_create_new = true
}

general {
  # Gaps and border
  gaps_in = 4
  gaps_out = 0
  gaps_workspaces = 50
  border_size = 0

  resize_on_border = true
  no_focus_fallback = true
  layout = dwindle

  allow_tearing = true # This just allows the `immediate` window rule to work
}

dwindle {
  preserve_split = true
  smart_split = false
  smart_resizing = false
}

decoration {
  rounding = 16
  blur {
    enabled = true
    new_optimizations = true
    popups = true
    popups_ignorealpha = 0.6
    xray = true
  }
  shadow {
    enabled = true
    ignore_window = true
    range = 20
    offset = 0 2
    render_power = 4
  }
  active_opacity = 0.9
  inactive_opacity = 0.7

  dim_inactive = false
  dim_strength = 0.2
  dim_special = 0
}

cursor {
  no_hardware_cursors = false
  hide_on_key_press = true
  inactive_timeout = 3
}

animations { 
  enabled = true
  bezier = wind, 0.05, 0.9, 0.1, 1.05
  bezier = winIn, 0.1, 1.1, 0.1, 1.1
  bezier = winOut, 0.3, -0.3, 0, 1
  bezier = liner, 1, 1, 1, 1
  animation = windows, 1, 3, wind, slide
  animation = windowsIn, 1, 3, winIn, slide
  animation = windowsOut, 1, 3, winOut, slide
  animation = windowsMove, 1, 3, wind, slide
  animation = border, 1, 1, liner
  animation = borderangle, 1, 30, liner, loop
  animation = fade, 1, 10, default
  animation = workspaces, 1, 5, wind, slidefade 20%
}

misc {
  vfr = 0
  vrr = 0
  animate_manual_resizes = true
  animate_mouse_windowdragging = false
  enable_swallow = false
  swallow_regex = (foot|kitty|allacritty|Alacritty)
  disable_hyprland_logo = true
  force_default_wallpaper = 0
  allow_session_lock_restore = 1
  initial_workspace_tracking = 1
  mouse_move_focuses_monitor = false
}

plugin {
  hyprsplit {
    num_workspaces = 9
  }
  hyprtasking {
    layout = grid
    gap_size = 20
    border_size = 2
    grid {
      gaps_use_aspect_ratio = false
    }
  }

  dynamic-cursors {
    enabled = true
    mode = stretch
    threshold = 2

    stretch {
      limit = 3000
      function = quadratic
      window = 100
    }

    shake {
      enabled = true
      nearest = true
      threshold = 9999999.0 # disable shake but still have magnify enabled through keybinds
      base = 4.0
      speed = 4.0
      influence = 0.0
      limit = 0.0
      timeout = 2000
      effects = false
      ipc = false
    }

    hyprcursor {
      nearest = true
      enabled = true
      resolution = -1
      fallback = clientside
    }
  }

}
