# Load annexes
zinit light-mode for \
  zdharma-continuum/zinit-annex-as-monitor \
  zdharma-continuum/zinit-annex-bin-gem-node \
  zdharma-continuum/zinit-annex-patch-dl \
  zdharma-continuum/zinit-annex-rust

# Plugins
zi ice lucid wait depth"1" atload"init_after_zvm"
zi light jeffreytse/zsh-vi-mode

ZVM_SYSTEM_CLIPBOARD_ENABLED=true
ZVM_INIT_MODE=sourcing

init_after_zvm() {
  bindkey -M viins '^n' history-forwards-or-complete
  bindkey -M viins '^p' history-backwards-or-complete
}

zi ice lucid wait depth"1"
zi light zsh-users/zsh-completions

# FZF History Widgets
fzf-history-backward() {
  local selected
  selected=$(fc -l 1 | sed 's/^[ ]*[0-9]\+\**[ ]*//' | fzf --tac +s --query "$LBUFFER")
  if [[ -n $selected ]]; then
    BUFFER="$selected"
    CURSOR=${#BUFFER}
    zle redisplay
  fi
}
zle -N fzf-history-backward

fzf-history-forward() {
  local selected
  selected=$(fc -l 1 | sed 's/^[ ]*[0-9]\+\**[ ]*//' | fzf +s --query "$LBUFFER")
  if [[ -n $selected ]]; then
    BUFFER="$selected"
    CURSOR=${#BUFFER}
    zle redisplay
  fi
}
zle -N fzf-history-forward

# Conditional history navigation
history-backwards-or-complete() {
  if [[ $LBUFFER == *[![:space:]]* ]]; then
    zle menu-select
  else
    fzf-history-backward
  fi
}
zle -N history-backwards-or-complete

history-forwards-or-complete() {
  if [[ $LBUFFER == *[![:space:]]* ]]; then
    zle menu-select
  else
    fzf-history-forward
  fi
}
zle -N history-forwards-or-complete

# Keybindings for autocomplete
init_autocomplete() {
  bindkey -M vicmd '^P' fzf-history-backward
  bindkey -M vicmd '^N' fzf-history-forward
  bindkey -M menuselect '^N' menu-complete
  bindkey -M menuselect '^P' reverse-menu-complete
  bindkey -M menuselect '^I' complete-word
  bindkey -M viins '^I' complete-word
}
zi ice lucid wait depth"1" atload"init_autocomplete"
zi light marlonrichert/zsh-autocomplete

# Autocomplete styling
zstyle ':autocomplete:*' append-semicolon no
zstyle ':autocomplete:*' list-lines 8
zstyle ':autocomplete:*' list-position below
zstyle ':autocomplete:*' min-input 1
zstyle ':autocomplete:*' delay 0.2

# More plugins
zi ice lucid wait depth"1"
zi snippet OMZP::fzf

zi ice lucid depth"1" wait atinit"zicompinit"
zi light zsh-users/zsh-syntax-highlighting

zi ice lucid depth"1" wait
zi light z-shell/zsh-lsd

zi ice lucid depth"1" wait
zi snippet OMZP::git

zi ice lucid wait atload"zsh-defer -t 2 init_keychain"
zi light romkatv/zsh-defer

# Environment variables
export PAGER="less -X -F"
export EDITOR="nvim"

# Utility functions
timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do
    time $shell -i -c exit
  done
}

pfwd() {
  if [ $# -ne 2 ]; then
    echo "Usage: pfwd <port> <host>"
    return 1
  fi
}

init_keychain() {
  eval "$(keychain --quiet --eval id_ed25519)"
}

# Set cursor style
echo -ne '\e[6 q'

