# styling
set -g pane-border-indicators off
set -g status-position top
set -g window-status-separator ""
set -g status-left-length 0

set -g status-style "bg=#{@thm_bg}"
set -g window-status-format "#[bg=#{@thm_muted},fg=#{@thm_bg}]#[bg=#{@thm_muted},fg=#{@thm_bg},bold] #W#{?window_zoomed_flag, ,} #[bg=#{@thm_bg},fg=#{@thm_muted}]"
set -g window-status-current-format "#[bg=#{@thm_accent},fg=#{@thm_bg}]#[bg=#{@thm_accent},fg=#{@thm_bg},bold] #W#{?window_zoomed_flag, ,} #[bg=#{@thm_bg},fg=#{@thm_accent}]"
set -g window-status-separator ""
set -g status-left "#[fg=#{@thm_fg} bold]#h (#S) #{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_accent} bold]NORMAL }}"
set -g status-right ""
set -g pane-border-style "fg=#{@thm_alt_bg}"
set -g pane-active-border-style "fg=#{@thm_alt_bg}"
